# UI Generator - assembles the final ui.odin file
# Collects callbacks from widgets and generates Callbacks struct + implementations
{ ui ? import ./default.nix
, widgetsDir ? ./Widgets
}:
let
  lib = builtins;

  # Get layout body from layout.nix
  layoutBody = import ./layout.nix { inherit ui widgetsDir; };

  # Collect all widget names from UI config
  getZoneWidgets = container: orientation:
    let
      start = if orientation == "horizontal"
              then container.left or []
              else container.top or [];
      center = container.center or [];
      end = if orientation == "horizontal"
            then container.right or []
            else container.bottom or [];
    in start ++ center ++ end;

  getEdgeWidgets = containers: orientation:
    lib.concatLists (map (c: getZoneWidgets c orientation) containers);

  allWidgetNames =
    (getEdgeWidgets (ui.top or []) "horizontal") ++
    (getEdgeWidgets (ui.bottom or []) "horizontal") ++
    (getEdgeWidgets (ui.left or []) "vertical") ++
    (getEdgeWidgets (ui.right or []) "vertical");

  # Remove duplicates
  uniqueWidgets = lib.foldl' (acc: name:
    if lib.elem name acc then acc else acc ++ [name]
  ) [] allWidgetNames;

  # Import widget and get its callbacks
  getWidgetCallbacks = name:
    let widget = import (widgetsDir + "/${name}.nix") { orientation = "horizontal"; };
    in widget.callbacks or {};

  # Collect all callbacks from all widgets
  allCallbacks = lib.foldl' (acc: name:
    acc // (getWidgetCallbacks name)
  ) {} uniqueWidgets;

  callbackNames = lib.attrNames allCallbacks;

  # Generate callback implementations
  callbackImpls = lib.concatStringsSep "\n\n" (map (name:
    allCallbacks.${name}.impl
  ) callbackNames);

  # Collect edge metadata for runtime show/hide system
  collectEdgeMeta = side: containers:
    let n = lib.length containers;
    in lib.genList (i:
      let
        container = lib.elemAt containers i;
      in {
        name = "edge_${side}_${toString i}";
        inherit side;
        show = container.show or "always";
        overlay = container.overlay or false;
      }
    ) n;

  allEdgeMeta =
    (collectEdgeMeta "top" (ui.top or [])) ++
    (collectEdgeMeta "bottom" (ui.bottom or [])) ++
    (collectEdgeMeta "left" (ui.left or [])) ++
    (collectEdgeMeta "right" (ui.right or []));

  edgeCount = lib.length allEdgeMeta;

  # Generate package-level global declarations for edge containers
  edgeGlobals = lib.concatStringsSep "\n" (map (e:
    "${e.name}: ^lv_obj_t"
  ) allEdgeMeta);

  # Generate edges array initialization code (inside build_ui)
  edgeArrayInit = lib.concatStringsSep "\n" (lib.genList (i:
    let e = lib.elemAt allEdgeMeta i;
        visible = if e.show == "always" then "true" else "false";
    in "    edges[${toString i}] = Edge_Info{obj = ${e.name}, name = \"${e.name}\", side = .${e.side}, show = .${e.show}, overlay = ${if e.overlay then "true" else "false"}, visible = ${visible}}"
  ) edgeCount);

in
''
// Axium Browser UI - Generated by Nix
// Do not edit manually

package axium

import "core:strings"
import "base:runtime"

// Package-level content area reference (queried by main.odin)
content_area: ^lv_obj_t

// Icon font (populated at init from compiled icon bitmaps)
icon_font: ^lv_font_t

// Edge container globals
${edgeGlobals}

// Edge show/hide metadata
Edge_Side :: enum { top, bottom, left, right }
Edge_Show :: enum { always, hover, toggle, hold }

Edge_Info :: struct {
    obj:     ^lv_obj_t,
    name:    string,
    side:    Edge_Side,
    show:    Edge_Show,
    overlay: bool,
    visible: bool,
}

edges: [${toString edgeCount}]Edge_Info

// Callback implementations - auto-generated from widgets
${callbackImpls}

// Build the UI
build_ui :: proc(screen: ^lv_obj_t, keyboard_group: ^lv_group_t) {
    icon_font = lv_onix_icons_get(font_size_base)
    if font_path != "" {
        cpath := strings.clone_to_cstring(strings.concatenate({"A:", font_path}))
        base_font := lv_tiny_ttf_create_file(cpath, font_size_base)
        if base_font != nil {
            lv_obj_set_style_text_font(screen, base_font, 0)
        }
    }
${layoutBody}

    // Populate edge metadata array
${edgeArrayInit}
}
''
