# UI Generator - assembles the final ui.odin file
# Collects callbacks from widgets and generates Callbacks struct + implementations
{ ui ? import ./default.nix
, widgetsDir ? ./Widgets
, theme ? {}
}:
let
  lib = builtins;

  # Get layout body from layout.nix
  layoutBody = import ./layout.nix { inherit ui widgetsDir theme; };

  # Collect all widget names from UI config
  getZoneWidgets = container: orientation:
    let
      start = if orientation == "horizontal"
              then container.left or []
              else container.top or [];
      center = container.center or [];
      end = if orientation == "horizontal"
            then container.right or []
            else container.bottom or [];
    in start ++ center ++ end;

  getEdgeWidgets = containers: orientation:
    lib.concatLists (map (c: getZoneWidgets c orientation) containers);

  allWidgetNames =
    (getEdgeWidgets (ui.top or []) "horizontal") ++
    (getEdgeWidgets (ui.bottom or []) "horizontal") ++
    (getEdgeWidgets (ui.left or []) "vertical") ++
    (getEdgeWidgets (ui.right or []) "vertical");

  # Remove duplicates
  uniqueWidgets = lib.foldl' (acc: name:
    if lib.elem name acc then acc else acc ++ [name]
  ) [] allWidgetNames;

  # Import widget and get its callbacks
  getWidgetCallbacks = name:
    let widget = import (widgetsDir + "/${name}.nix") { orientation = "horizontal"; };
    in widget.callbacks or {};

  # Collect all callbacks from all widgets
  allCallbacks = lib.foldl' (acc: name:
    acc // (getWidgetCallbacks name)
  ) {} uniqueWidgets;

  callbackNames = lib.attrNames allCallbacks;

  # Generate callback implementations
  callbackImpls = lib.concatStringsSep "\n\n" (map (name:
    allCallbacks.${name}.impl
  ) callbackNames);

in
''
// Axium Browser UI - Generated by Nix
// Do not edit manually

package ui

import "core:fmt"
import lvgl "../lvgl"

// UI State
State :: struct {
    url_input: ^lvgl.lv_obj_t,
}

// Callback implementations - auto-generated from widgets
${callbackImpls}

// Build the UI
build_ui :: proc(screen: ^lvgl.lv_obj_t, keyboard_group: ^lvgl.lv_group_t, state: ^State) {
${layoutBody}
}
''
